config/routes.rb
Coffee2604::Application.routes.draw do
	match "/coffee_houses/average"
	match "/coffee_houses/average_customized"
	match "/coffee_ratings/recover"
	match "/coffee_ratings/rate_averages"
	match "/addresses/find_by_coffee_house"
	match "/addresses/find_by_roaster"
	match "/addresses/find_by_cup_manufacturer"
	match "/addresses/find_by_machine_manufacturer"

  resources :addresses

  resources :coffee_ratings

  resources :coffee_houses

  resources :reviewers

  resources :cup_manufacturers

  resources :roasters

  resources :machine_manufacturers

end

app/models/reviewer.rb
class Reviewer < ActiveRecord::Base
  has_many :coffee_houses
  has_one :coffee_rating   
  validates :name, :presence => true 
  validates :email,	:format => {:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i}
     
  attr_accessible :email, :name, :nickname, :reviewer_type
end

app/controllers/reviewers_controller.rb
class ReviewersController < ApplicationController
  # GET /reviewers
  # GET /reviewers.json
  def index
    @reviewers = Reviewer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reviewers }
    end
  end

  # GET /reviewers/1
  # GET /reviewers/1.json
  def show
    @reviewer = Reviewer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reviewer }
    end
  end

  # GET /reviewers/new
  # GET /reviewers/new.json
  def new
    @reviewer = Reviewer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reviewer }
    end
  end

  # GET /reviewers/1/edit
  def edit
    @reviewer = Reviewer.find(params[:id])
  end

  # POST /reviewers
  # POST /reviewers.json
  def create
    @reviewer = Reviewer.new(params[:reviewer])

    respond_to do |format|
      if @reviewer.save
        format.html { redirect_to @reviewer, notice: 'Reviewer was successfully created.' }
        format.json { render json: @reviewer, status: :created, location: @reviewer }
      else
        format.html { render action: "new" }
        format.json { render json: @reviewer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reviewers/1
  # PUT /reviewers/1.json
  def update
    @reviewer = Reviewer.find(params[:id])

    respond_to do |format|
      if @reviewer.update_attributes(params[:reviewer])
        format.html { redirect_to @reviewer, notice: 'Reviewer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reviewer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviewers/1
  # DELETE /reviewers/1.json
  def destroy
    @reviewer = Reviewer.find(params[:id])
    @reviewer.destroy

    respond_to do |format|
      format.html { redirect_to reviewers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/reviewers_helper.rb
module ReviewersHelper
end

app/views/reviewers/_form.html.erb
<%= form_for(@reviewer) do |f| %>
  <% if @reviewer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reviewer.errors.count, "error") %> prohibited this reviewer from being saved:</h2>

      <ul>
      <% @reviewer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :nickname %><br />
    <%= f.text_field :nickname %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :reviewer_type %><br />
    <%= f.text_field :reviewer_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviewers/edit.html.erb
<h1>Editing reviewer</h1>

<%= render 'form' %>

<%= link_to 'Show', @reviewer %> |
<%= link_to 'Back', reviewers_path %>

app/views/reviewers/index.html.erb
<h1>Listing reviewers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Nickname</th>
    <th>Email</th>
    <th>Reviewer type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reviewers.each do |reviewer| %>
  <tr>
    <td><%= reviewer.name %></td>
    <td><%= reviewer.nickname %></td>
    <td><%= reviewer.email %></td>
    <td><%= reviewer.reviewer_type %></td>
    <td><%= link_to 'Show', reviewer %></td>
    <td><%= link_to 'Edit', edit_reviewer_path(reviewer) %></td>
    <td><%= link_to 'Destroy', reviewer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reviewer', new_reviewer_path %>

app/views/reviewers/new.html.erb
<h1>New reviewer</h1>

<%= render 'form' %>

<%= link_to 'Back', reviewers_path %>

app/views/reviewers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @reviewer.name %>
</p>

<p>
  <b>Nickname:</b>
  <%= @reviewer.nickname %>
</p>

<p>
  <b>Email:</b>
  <%= @reviewer.email %>
</p>

<p>
  <b>Reviewer type:</b>
  <%= @reviewer.reviewer_type %>
</p>


<%= link_to 'Edit', edit_reviewer_path(@reviewer) %> |
<%= link_to 'Back', reviewers_path %>