config/routes.rb
Coffee2604::Application.routes.draw do
	match "/coffee_houses/average"
	match "/coffee_houses/average_customized"
	match "/coffee_ratings/recover"
	match "/coffee_ratings/rate_averages"
	match "/addresses/find_by_coffee_house"
	match "/addresses/find_by_roaster"
	match "/addresses/find_by_cup_manufacturer"
	match "/addresses/find_by_machine_manufacturer"

  resources :addresses

  resources :coffee_ratings

  resources :coffee_houses

  resources :reviewers

  resources :cup_manufacturers

  resources :roasters

  resources :machine_manufacturers

end

app/models/machine_manufacturer.rb
class MachineManufacturer < ActiveRecord::Base
  has_many :coffee_houses
  has_one :address, :as => :addressable
    attr_accessible :comments, :groups, :models, :name, :types, :website, :created_at, :updated_at, :address
  validates :name, :presence => true
end

app/controllers/machine_manufacturers_controller.rb
class MachineManufacturersController < ApplicationController
  # GET /machine_manufacturers
  # GET /machine_manufacturers.json
  def index
    @machine_manufacturers = MachineManufacturer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @machine_manufacturers }
    end
  end

  # GET /machine_manufacturers/1
  # GET /machine_manufacturers/1.json
  def show
    @machine_manufacturer = MachineManufacturer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @machine_manufacturer }
    end
  end

  # GET /machine_manufacturers/new
  # GET /machine_manufacturers/new.json
  def new
    @machine_manufacturer = MachineManufacturer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @machine_manufacturer }
    end
  end

  # GET /machine_manufacturers/1/edit
  def edit
    @machine_manufacturer = MachineManufacturer.find(params[:id])
  end

  # POST /machine_manufacturers
  # POST /machine_manufacturers.json
  def create
    @machine_manufacturer = MachineManufacturer.new(params[:machine_manufacturer])

    respond_to do |format|
      if @machine_manufacturer.save
        format.html { redirect_to @machine_manufacturer, notice: 'Machine manufacturer was successfully created.' }
        format.json { render json: @machine_manufacturer, status: :created, location: @machine_manufacturer }
      else
        format.html { render action: "new" }
        format.json { render json: @machine_manufacturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /machine_manufacturers/1
  # PUT /machine_manufacturers/1.json
  def update
    @machine_manufacturer = MachineManufacturer.find(params[:id])

    respond_to do |format|
      if @machine_manufacturer.update_attributes(params[:machine_manufacturer])
        format.html { redirect_to @machine_manufacturer, notice: 'Machine manufacturer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @machine_manufacturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /machine_manufacturers/1
  # DELETE /machine_manufacturers/1.json
  def destroy
    @machine_manufacturer = MachineManufacturer.find(params[:id])
    @machine_manufacturer.destroy

    respond_to do |format|
      format.html { redirect_to machine_manufacturers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/machine_manufacturers_helper.rb
module MachineManufacturersHelper
end

app/views/machine_manufacturers/_form.html.erb
<%= form_for(@machine_manufacturer) do |f| %>
  <% if @machine_manufacturer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@machine_manufacturer.errors.count, "error") %> prohibited this machine_manufacturer from being saved:</h2>

      <ul>
      <% @machine_manufacturer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :types %><br />
    <%= f.text_field :types %>
  </div>
  <div class="field">
    <%= f.label :groups %><br />
    <%= f.text_field :groups %>
  </div>
  <div class="field">
    <%= f.label :models %><br />
    <%= f.text_field :models %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_area :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/machine_manufacturers/edit.html.erb
<h1>Editing machine_manufacturer</h1>

<%= render 'form' %>

<%= link_to 'Show', @machine_manufacturer %> |
<%= link_to 'Back', machine_manufacturers_path %>

app/views/machine_manufacturers/index.html.erb
<h1>Listing machine_manufacturers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Types</th>
    <th>Groups</th>
    <th>Models</th>
    <th>Website</th>
    <th>Comments</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @machine_manufacturers.each do |machine_manufacturer| %>
  <tr>
    <td><%= machine_manufacturer.name %></td>
    <td><%= machine_manufacturer.types %></td>
    <td><%= machine_manufacturer.groups %></td>
    <td><%= machine_manufacturer.models %></td>
    <td><%= machine_manufacturer.website %></td>
    <td><%= machine_manufacturer.comments %></td>
    <td><%= link_to 'Show', machine_manufacturer %></td>
    <td><%= link_to 'Edit', edit_machine_manufacturer_path(machine_manufacturer) %></td>
    <td><%= link_to 'Destroy', machine_manufacturer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Machine manufacturer', new_machine_manufacturer_path %>

app/views/machine_manufacturers/new.html.erb
<h1>New machine_manufacturer</h1>

<%= render 'form' %>

<%= link_to 'Back', machine_manufacturers_path %>

app/views/machine_manufacturers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @machine_manufacturer.name %>
</p>

<p>
  <b>Types:</b>
  <%= @machine_manufacturer.types %>
</p>

<p>
  <b>Groups:</b>
  <%= @machine_manufacturer.groups %>
</p>

<p>
  <b>Models:</b>
  <%= @machine_manufacturer.models %>
</p>

<p>
  <b>Website:</b>
  <%= @machine_manufacturer.website %>
</p>

<p>
  <b>Comments:</b>
  <%= @machine_manufacturer.comments %>
</p>


<%= link_to 'Edit', edit_machine_manufacturer_path(@machine_manufacturer) %> |
<%= link_to 'Back', machine_manufacturers_path %>