config/routes.rb
Coffee2604::Application.routes.draw do
	match "/coffee_houses/average"
	match "/coffee_houses/average_customized"
	match "/coffee_ratings/recover"
	match "/coffee_ratings/rate_averages"
	match "/addresses/find_by_coffee_house"
	match "/addresses/find_by_roaster"
	match "/addresses/find_by_cup_manufacturer"
	match "/addresses/find_by_machine_manufacturer"

  resources :addresses

  resources :coffee_ratings

  resources :coffee_houses

  resources :reviewers

  resources :cup_manufacturers

  resources :roasters

  resources :machine_manufacturers

end

app/models/roaster.rb
class Roaster < ActiveRecord::Base
  has_many :coffee_houses
  has_one :address, :as => :addressable
  validates :name, :presence => true
  attr_accessible :blends, :comments, :name, :website, :created_at, :updated_at, :address
end

app/controllers/roasters_controller.rb
class RoastersController < ApplicationController
  # GET /roasters
  # GET /roasters.json
  def index
    @roasters = Roaster.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roasters }
    end
  end

  # GET /roasters/1
  # GET /roasters/1.json
  def show
    @roaster = Roaster.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @roaster }
    end
  end

  # GET /roasters/new
  # GET /roasters/new.json
  def new
    @roaster = Roaster.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @roaster }
    end
  end

  # GET /roasters/1/edit
  def edit
    @roaster = Roaster.find(params[:id])
  end

  # POST /roasters
  # POST /roasters.json
  def create
    @roaster = Roaster.new(params[:roaster])

    respond_to do |format|
      if @roaster.save
        format.html { redirect_to @roaster, notice: 'Roaster was successfully created.' }
        format.json { render json: @roaster, status: :created, location: @roaster }
      else
        format.html { render action: "new" }
        format.json { render json: @roaster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /roasters/1
  # PUT /roasters/1.json
  def update
    @roaster = Roaster.find(params[:id])

    respond_to do |format|
      if @roaster.update_attributes(params[:roaster])
        format.html { redirect_to @roaster, notice: 'Roaster was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @roaster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roasters/1
  # DELETE /roasters/1.json
  def destroy
    @roaster = Roaster.find(params[:id])
    @roaster.destroy

    respond_to do |format|
      format.html { redirect_to roasters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/roasters_helper.rb
module RoastersHelper
end

app/views/roasters/_form.html.erb
<%= form_for(@roaster) do |f| %>
  <% if @roaster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@roaster.errors.count, "error") %> prohibited this roaster from being saved:</h2>

      <ul>
      <% @roaster.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :blends %><br />
    <%= f.text_field :blends %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_area :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roasters/edit.html.erb
<h1>Editing roaster</h1>

<%= render 'form' %>

<%= link_to 'Show', @roaster %> |
<%= link_to 'Back', roasters_path %>

app/views/roasters/index.html.erb
<h1>Listing roasters</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Blends</th>
    <th>Website</th>
    <th>Comments</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @roasters.each do |roaster| %>
  <tr>
    <td><%= roaster.name %></td>
    <td><%= roaster.blends %></td>
    <td><%= roaster.website %></td>
    <td><%= roaster.comments %></td>
    <td><%= link_to 'Show', roaster %></td>
    <td><%= link_to 'Edit', edit_roaster_path(roaster) %></td>
    <td><%= link_to 'Destroy', roaster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Roaster', new_roaster_path %>

app/views/roasters/new.html.erb
<h1>New roaster</h1>

<%= render 'form' %>

<%= link_to 'Back', roasters_path %>

app/views/roasters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @roaster.name %>
</p>

<p>
  <b>Blends:</b>
  <%= @roaster.blends %>
</p>

<p>
  <b>Website:</b>
  <%= @roaster.website %>
</p>

<p>
  <b>Comments:</b>
  <%= @roaster.comments %>
</p>


<%= link_to 'Edit', edit_roaster_path(@roaster) %> |
<%= link_to 'Back', roasters_path %>